language: android

sudo: false

android:
  components:
    - android-28
    - build-tools-28.0.3
licenses:
  - 'android-sdk-license-.+'

before_install:
  - chmod +x gradlew

script: ./gradlew clean testReleaseUnitTest assembleRelease javadocJar sourcesJar

notifications:
  email: false
