os: linux
dist: xenial
language: android

before_cache:
- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/journal-1/
- rm -f  $HOME/.gradle/caches/transforms-1/transforms-1.lock
- rm -f  $HOME/.gradle/caches/*/javaCompile/javaCompile.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/
- rm -fr $HOME/.gradle/caches/*/fileHashes/
cache:
  directories:
  - $HOME/.gradle/caches/
  - $HOME/.gradle/wrapper/

jdk:
  - openjdk11
android:
  components:
    - android-29
    - build-tools-29.0.3
  licenses:
    - 'android-sdk-license-.+'

before_install:
  - chmod +x gradlew

script:
  - printenv
  - . ./.travis/prepareSonarAnalysis.sh
  - ./gradlew clean testReleaseUnitTest sonarqube assembleRelease kdocJar sourcesJar

deploy:
  provider: script
  script: ./gradlew :android-beans:bintrayUpload
  cleanup: true
  on:
    tags: true

notifications:
  email: false
