name: Build-Pipeline

on: [ push, pull_request ]

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '11'
      - name: Cache gradle distribution
        uses: actions/cache@v2
        with:
          path: ~/.gradle/wrapper/dists
          key: gradle-dists-${{ hashFiles('gradle/wrapper/gradle-wrapper.properties') }}
      - name: Cache gradle dependencies
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches/modules-2
          key: gradle-deps-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            gradle-dists-
      - name: Build and check library
        run: |
          chmod +x gradlew
          ./gradlew --no-daemon --stacktrace \
          lintRelease testReleaseUnitTest \
          assembleRelease kdocJar sourcesJar
      - name: Archive lint results
        uses: actions/upload-artifact@v2
        with:
          name: lint-report
          path: android-beans/build/reports/lint-results-release.*
      - name: Archive teset results
        uses: actions/upload-artifact@v2
        with:
          name: test-report
          path: android-beans/build/reports/tests/testReleaseUnitTest/**/*
      - name: Archive aar
        uses: actions/upload-artifact@v2
        with:
          name: aar
          path: android-beans/build/outputs/aar/android-beans-*.aar
      - name: Archive kdoc
        uses: actions/upload-artifact@v2
        with:
          name: kdoc
          path: android-beans/build/libs/android-beans-*-kdoc.jar
      - name: Archive sources
        uses: actions/upload-artifact@v2
        with:
          name: sources
          path: android-beans/build/libs/android-beans-*-sources.jar
