name: Build-Pipeline

on: [ push, pull_request ]

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '11'
      - name: Build and check library
        run: |
          chmod +x gradlew
          ./gradlew --no-daemon --stacktrace \
          lintRelease testReleaseUnitTest \
          assembleRelease kdocJar sourcesJar
